// client/src/lib/components/Input.svelte
<script lang="ts">
	export let variant: 'primary' | 'secondary' | undefined = undefined;
	export let className = '';
	export { className as class };
</script>

<input
	class="input input-bordered {className}"
	class:input-primary={variant === 'primary'}
	class:input-secondary={variant === 'secondary'}
	{...$$restProps}
/>

// client-react/components/ui/Input.tsx
import classNames from 'classnames';

interface InputProps extends React.ComponentProps<'input'> {
  variant?: 'primary' | 'secondary';
}

export function Input(props: InputProps) {
  const inputClass = classNames({
    'input-primary': props.variant === 'primary',
    'input-secondary': props.variant === 'secondary',
  });

  return (
    <input
      className={`input input-bordered ${inputClass} ${props.className}`}
      {...props}
    />
  );
}
