// client-react/components/ui/Button.tsx
import classNames from "classnames";

interface ButtonProps extends React.ComponentProps<"button"> {
  color?: 'primary' | 'secondary' | 'accent';
  variant?: 'outlined'
}

export function Button(props: ButtonProps) {
  const { className, children, ...otherProps } = props;
  const btnClass = classNames({
    'btn-primary': props.color === 'primary',
    'btn-accent': props.color === 'accent',
    'btn-secondary': props.color === 'secondary',
    'btn-outline': props.variant === 'outlined',
  })

  return (
    <button className={`btn ${btnClass} ${props.className}`} {...otherProps}>{children}</button>
  );
}

// client/src/lib/components/Button.svelte
<script lang="ts">
	export let color: 'primary' | 'secondary' | 'accent' | undefined = undefined;
	export let variant: 'outlined' | undefined = undefined;
	export let className = '';
	export { className as class };
</script>

<button
	{...$$restProps}
	on:click
	class="btn {className}"
	class:btn-primary={color === 'primary'}
	class:btn-secondary={color === 'secondary'}
	class:btn-accent={color === 'accent'}
	class:btn-outline={variant === 'outlined'}
>
	<slot />
</button>
